Repository codestates-seb/seb45_pre_016, pull requests merged in 2023-08, with the labels that each got.

#16 feat : user CRUD 기능 추가 - v1
  server/src/main/java/com/codestates/server/user/controller/UserController.java
  server/src/main/java/com/codestates/server/user/dto/UserLoginDto.java
  server/src/main/java/com/codestates/server/user/dto/UserPatchDto.java
  server/src/main/java/com/codestates/server/user/dto/UserPostDto.java
  server/src/main/java/com/codestates/server/user/dto/UserResponseDto.java
  server/src/main/java/com/codestates/server/user/entity/User.java
  server/src/main/java/com/codestates/server/user/mapper/UserMapper.java
  server/src/main/java/com/codestates/server/user/repository/UserRepository.java
  server/src/main/java/com/codestates/server/user/service/UserService.java
Labels: [BE]솔이, BackEnd

#23 feat : answer CRUD 기능 추가
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerPatchDto.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerPostDto.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerResponseDto.java
  server/src/main/java/com/codestates/server/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/answer/mapper/AnswerMapper.java
  server/src/main/java/com/codestates/server/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/user/repository/UserRepository.java
  server/src/main/java/com/codestates/server/user/service/UserService.java
Labels: [BE]인수, BackEnd

#27 feat: Question CRUD
  server/src/main/java/com/codestates/server/question/CHECK.md
  server/src/main/java/com/codestates/server/question/controller/QuestionController.java
  server/src/main/java/com/codestates/server/question/dto/QuestionPatchDto.java
  server/src/main/java/com/codestates/server/question/dto/QuestionPostDto.java
  server/src/main/java/com/codestates/server/question/dto/QuestionResponseDto.java
  server/src/main/java/com/codestates/server/question/dto/Response.java
  server/src/main/java/com/codestates/server/question/entity/Question.java
  server/src/main/java/com/codestates/server/question/mapper/QuestionMapper.java
  server/src/main/java/com/codestates/server/question/repository/QuestionRepository.java
  server/src/main/java/com/codestates/server/question/service/QuestionService.java
  server/src/main/java/com/codestates/server/question/uri/UriCreator.java
Labels: [BE]해영, BackEnd

#29 others : PR 하겠습니다..!
  server/src/main/java/com/codestates/server/user/dto/UserResponseDto.java
  server/src/main/java/com/codestates/server/user/entity/User.java
  server/src/main/java/com/codestates/server/user/service/UserService.java
Labels: [BE]솔이, BackEnd

#31 feat : tag 기능 추가
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerPatchDto.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerPostDto.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerResponseDto.java
  server/src/main/java/com/codestates/server/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/answer/mapper/AnswerMapper.java
  server/src/main/java/com/codestates/server/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/dto/MultiResponseDto.java
  server/src/main/java/com/codestates/server/dto/PageInfo.java
  server/src/main/java/com/codestates/server/question/dto/Response.java
  server/src/main/java/com/codestates/server/question/entity/Question.java
  server/src/main/java/com/codestates/server/question/uri/UriCreator.java
  server/src/main/java/com/codestates/server/tag/controller/TagController.java
  server/src/main/java/com/codestates/server/tag/dto/TagPostDto.java
  server/src/main/java/com/codestates/server/tag/dto/TagResponseDto.java
  server/src/main/java/com/codestates/server/tag/entity/Tag.java
  server/src/main/java/com/codestates/server/tag/mapper/TagMapper.java
  server/src/main/java/com/codestates/server/tag/repository/TagRepository.java
  server/src/main/java/com/codestates/server/tag/service/TagService.java
  server/src/main/java/com/codestates/server/user/controller/UserController.java
  server/src/main/java/com/codestates/server/user/dto/UserLoginDto.java
  server/src/main/java/com/codestates/server/user/dto/UserLoginResponseDto.java
  server/src/main/java/com/codestates/server/user/dto/UserPatchDto.java
  server/src/main/java/com/codestates/server/user/dto/UserPostDto.java
  server/src/main/java/com/codestates/server/user/dto/UserResponseDto.java
  server/src/main/java/com/codestates/server/user/entity/User.java
  server/src/main/java/com/codestates/server/user/mapper/UserMapper.java
  server/src/main/java/com/codestates/server/user/service/UserService.java
Labels: [BE]솔이, BackEnd

#32 misc: merge충돌
  server/src/main/java/com/codestates/server/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/answer/mapper/AnswerMapper.java
  server/src/main/java/com/codestates/server/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/question/controller/QuestionController.java
  server/src/main/java/com/codestates/server/question/dto/QuestionPostDto.java
  server/src/main/java/com/codestates/server/question/dto/QuestionResponseDto.java
  server/src/main/java/com/codestates/server/question/dto/Response.java
  server/src/main/java/com/codestates/server/question/entity/Question.java
  server/src/main/java/com/codestates/server/question/mapper/QuestionMapper.java
Labels: [BE]해영, BackEnd

#35 Others : 임시 수정완료
  .idea/workspace.xml
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerPatchDto.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerPostDto.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerResponseDto.java
  server/src/main/java/com/codestates/server/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/answer/mapper/AnswerMapper.java
  server/src/main/java/com/codestates/server/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/user/dto/UserLoginDto.java
Labels: enhancement, [BE]인수, BackEnd

#40 Feat/questiontag
  server/src/main/java/com/codestates/server/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/answer/mapper/AnswerMapper.java
  server/src/main/java/com/codestates/server/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/question/controller/QuestionController.java
  server/src/main/java/com/codestates/server/question/dto/QuestionPatchDto.java
  server/src/main/java/com/codestates/server/question/dto/QuestionPostDto.java
  server/src/main/java/com/codestates/server/question/dto/QuestionResponseDto.java
  server/src/main/java/com/codestates/server/question/entity/Question.java
  server/src/main/java/com/codestates/server/question/entity/QuestionTag.java
  server/src/main/java/com/codestates/server/question/mapper/QuestionMapper.java
  server/src/main/java/com/codestates/server/question/repository/QuestionTagRepository.java
  server/src/main/java/com/codestates/server/question/service/QuestionService.java
  server/src/main/java/com/codestates/server/tag/controller/TagController.java
  server/src/main/java/com/codestates/server/tag/entity/Tag.java
  server/src/main/java/com/codestates/server/tag/service/TagService.java
Labels: [BE]솔이, [BE]해영, [BE]인수, BackEnd

#45 other: CICD
  .github/workflows/deploy.yml
  server/build.gradle
  server/deploy.yaml
  server/scripts/start.sh
  server/scripts/stop.sh
  server/src/main/generated/com/codestates/server/answer/mapper/AnswerMapperImpl.java
  server/src/main/generated/com/codestates/server/question/mapper/QuestionMapperImpl.java
  server/src/main/generated/com/codestates/server/tag/mapper/TagMapperImpl.java
  server/src/main/generated/com/codestates/server/user/mapper/UserMapperImpl.java
Labels: [BE]솔이, [BE]해영, [BE]인수, BackEnd

#46 feat: security - jwt 기능 추가 및 ErrorResponse 추가
  server/src/main/java/com/codestates/server/response/ErrorResponse.java
  server/src/main/java/com/codestates/server/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/security/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/server/security/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/server/security/auth/handler/UserAccessDeniedHandlerIpl.java
  server/src/main/java/com/codestates/server/security/auth/handler/UserAuthenticationEntryPointImp.java
  server/src/main/java/com/codestates/server/security/auth/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/server/security/auth/handler/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/codestates/server/security/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/server/security/auth/utils/ErrorResponder.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/user/controller/UserController.java
  server/src/main/resources/application.yml
Labels: [BE]솔이, BackEnd

#52 docs : 수정완료
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/answer/mapper/AnswerMapper.java
  server/src/main/java/com/codestates/server/answer/service/AnswerService.java
Labels: documentation, [BE]인수, BackEnd

#54 Dev be
  .github/workflows/deploy.yml
  server/appspec.yml
  server/deploy.yaml
  server/scripts/start.sh
  server/src/main/generated/com/codestates/server/answer/mapper/AnswerMapperImpl.java
  server/src/main/generated/com/codestates/server/question/mapper/QuestionMapperImpl.java
  server/src/main/generated/com/codestates/server/tag/mapper/TagMapperImpl.java
  server/src/main/generated/com/codestates/server/user/mapper/UserMapperImpl.java
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerPostDto.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerResponseDto.java
  server/src/main/java/com/codestates/server/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/answer/mapper/AnswerMapper.java
  server/src/main/java/com/codestates/server/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/question/CHECK.md
  server/src/main/java/com/codestates/server/question/controller/QuestionController.java
  server/src/main/java/com/codestates/server/question/dto/QuestionResponseDto.java
  server/src/main/java/com/codestates/server/question/dto/Response.java
  server/src/main/java/com/codestates/server/question/entity/Question.java
  server/src/main/java/com/codestates/server/question/entity/QuestionTag.java
  server/src/main/java/com/codestates/server/question/mapper/QuestionMapper.java
  server/src/main/java/com/codestates/server/question/service/QuestionService.java
  server/src/main/java/com/codestates/server/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/security/config/SecurityCorsConfig.java
  server/src/main/java/com/codestates/server/tag/controller/TagController.java
  server/src/main/java/com/codestates/server/tag/dto/TagResponseDto.java
  server/src/main/java/com/codestates/server/tag/entity/Tag.java
  server/src/main/java/com/codestates/server/tag/mapper/TagMapper.java
  server/src/main/java/com/codestates/server/tag/repository/TagRepository.java
  server/src/main/java/com/codestates/server/tag/service/TagService.java
  server/src/main/java/com/codestates/server/user/controller/UserController.java
  server/src/main/resources/application.yml
Labels: [BE]솔이, [BE]해영, [BE]인수, BackEnd

#56 !hotfix: CORS 수정
  server/src/main/generated/com/codestates/server/answer/mapper/AnswerMapperImpl.java
  server/src/main/generated/com/codestates/server/question/mapper/QuestionMapperImpl.java
  server/src/main/generated/com/codestates/server/tag/mapper/TagMapperImpl.java
  server/src/main/generated/com/codestates/server/user/mapper/UserMapperImpl.java
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/dto/AnswerPatchDto.java
  server/src/main/java/com/codestates/server/question/dto/QuestionPatchDto.java
  server/src/main/java/com/codestates/server/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/security/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/security/config/SecurityCorsConfig.java
  server/src/main/java/com/codestates/server/tag/entity/Tag.java
Labels: [FE]인승, [BE]솔이, [BE]해영, BackEnd

#58 feat : 예외처리 추가
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/exception/BusinessLogicException.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/server/response/ErrorResponse.java
Labels: enhancement, [BE]인수, BackEnd

#59 feat: user 검증 기능 추가
  server/src/main/java/com/codestates/server/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/auth/utils/AuthUserUtils.java
  server/src/main/java/com/codestates/server/question/repository/QuestionRepository.java
  server/src/main/java/com/codestates/server/security/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/security/config/SecurityCorsConfig.java
  server/src/main/java/com/codestates/server/user/controller/UserController.java
  server/src/main/java/com/codestates/server/user/dto/UserPatchDto.java
  server/src/main/java/com/codestates/server/user/dto/UserResponseDto.java
  server/src/main/java/com/codestates/server/user/entity/User.java
  server/src/main/java/com/codestates/server/user/entity/UserAnswerInfo.java
  server/src/main/java/com/codestates/server/user/entity/UserQuestionInfo.java
  server/src/main/java/com/codestates/server/user/mapper/UserMapper.java
  server/src/main/java/com/codestates/server/user/service/UserService.java
Labels: [BE]솔이, BackEnd

#60 Dev be
  server/scripts/start.sh
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/question/CHECK.md
  server/src/main/java/com/codestates/server/question/controller/QuestionController.java
  server/src/main/java/com/codestates/server/question/dto/QuestionResponseDto.java
  server/src/main/java/com/codestates/server/question/service/QuestionService.java
Labels: [BE]솔이, [BE]해영, [BE]인수, BackEnd

#62 feat: answer수정
  server/src/main/generated/com/codestates/server/answer/mapper/AnswerMapperImpl.java
  server/src/main/generated/com/codestates/server/question/mapper/QuestionMapperImpl.java
  server/src/main/generated/com/codestates/server/tag/mapper/TagMapperImpl.java
  server/src/main/generated/com/codestates/server/user/mapper/UserMapperImpl.java
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/audit/TimeStamp.java
  server/src/main/java/com/codestates/server/auth/utils/AuthUserUtils.java
  server/src/main/java/com/codestates/server/exception/ExceptionCode.java
  server/src/main/java/com/codestates/server/question/controller/QuestionController.java
  server/src/main/java/com/codestates/server/question/dto/QuestionPatchDto.java
  server/src/main/java/com/codestates/server/question/dto/QuestionPostDto.java
  server/src/main/java/com/codestates/server/question/entity/Question.java
  server/src/main/java/com/codestates/server/question/mapper/QuestionMapper.java
  server/src/main/java/com/codestates/server/question/repository/QuestionRepository.java
  server/src/main/java/com/codestates/server/question/service/QuestionService.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/user/entity/User.java
  server/src/main/java/com/codestates/server/user/service/UserService.java
Labels: [BE]솔이, [BE]해영, [BE]인수, BackEnd

#70 docs : 예외처리 추가 및 예외메세지 추가
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/entity/Answer.java
  server/src/main/java/com/codestates/server/answer/mapper/AnswerMapper.java
  server/src/main/java/com/codestates/server/answer/service/AnswerService.java
  server/src/main/java/com/codestates/server/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/server/user/entity/User.java
  server/src/main/java/com/codestates/server/user/service/UserService.java
Labels: documentation, [BE]인수, BackEnd

#77 CORS 수정
  server/src/main/java/com/codestates/server/question/service/QuestionService.java
  server/src/main/java/com/codestates/server/security/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/server/security/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
Labels: [BE]솔이, [BE]해영, [BE]인수, BackEnd

#80 rename: User 예외처리 수정
  .idea/aws.xml
  .idea/vcs.xml
  .idea/workspace.xml
  README.md
  server/src/main/generated/com/codestates/server/user/mapper/UserMapperImpl.java
  server/src/main/java/com/codestates/server/question/service/QuestionService.java
  server/src/main/java/com/codestates/server/security/auth/userdetails/UserDetailsServiceImpl.java
  server/src/main/java/com/codestates/server/security/auth/utils/AuthUserUtils.java
  server/src/main/java/com/codestates/server/security/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/server/user/entity/User.java
  server/src/main/java/com/codestates/server/user/service/UserService.java
Labels: [BE]솔이, [BE]해영, [BE]인수, BackEnd

#81 docs : 전체 예외처리 완료
  server/src/main/java/com/codestates/server/exception/GlobalExceptionAdvice.java
Labels: documentation, [BE]솔이, [BE]해영, [BE]인수, BackEnd

#82 DEV be
  server/src/main/generated/com/codestates/server/answer/mapper/AnswerMapperImpl.java
  server/src/main/java/com/codestates/server/answer/controller/AnswerController.java
  server/src/main/java/com/codestates/server/answer/repository/AnswerRepository.java
  server/src/main/java/com/codestates/server/question/controller/QuestionController.java
  server/src/main/java/com/codestates/server/question/entity/Question.java
  server/src/main/resources/application.yml
Labels: [BE]솔이, [BE]해영, [BE]인수, BackEnd
